version: "3"
services:
  client1:
    image: sk-big-2
    command: sh -c "./sk-big-2/radio-client -H 255.255.255.255 -P 16000 -p 8000 > ./data/out.mp3"
    volumes:
      - ./data/client1:/home/hugodutka/data/
  client2:
    image: sk-big-2
    command: sh -c "./sk-big-2/radio-client -H 255.255.255.255 -P 16000 -p 8000 > ./data/out.mp3"
    volumes:
      - ./data/client2:/home/hugodutka/data/
  proxy1:
    image: sk-big-2
    command: ./sk-big-2/radio-proxy "-h" "ant-waw-01.cdn.eurozet.pl" "-r" "/" "-p" "8602" "-m" "yes" "-P" "16000"
  proxy2:
    image: sk-big-2
    command: ./sk-big-2/radio-proxy "-h" "waw02-03.ic.smcdn.pl" "-r" "/t050-1.mp3" "-p" "8000" "-m" "yes" "-P" "16000"
  proxy3:
    image: sk-big-2
    command: ./sk-big-2/radio-proxy "-h" "78.31.65.20" "-r" "/dance.mp3" "-p" "8080" "-m" "yes" "-P" "16000"
  proxy4:
    image: sk-big-2
    command: ./sk-big-2/radio-proxy "-h" "waw02-03.ic.smcdn.pl" "-r" "/t050-1.mp3" "-p" "8000" "-m" "yes" "-P" "16000"
